#define NOP instruction_00
#define ADDI8 instruction_03
#define JMP0 instruction_04
#define ENI instruction_05
#define DECA instruction_07
#define IN1 instruction_09
#define IN2 instruction_0a
#define MOVDAP4 instruction_0c
#define MOVDAP5 instruction_0d
#define MOVDAP6 instruction_0e
#define MOVDAP7 instruction_0f
#define INCIR0 instruction_10
#define INCIR1 instruction_11
#define ADDCI8 instruction_13
#define CALL0 instruction_14
#define DISI instruction_15
#define INCA instruction_17
#define INCR0 instruction_18
#define INCR1 instruction_19
#define INCR2 instruction_1a
#define INCR3 instruction_1b
#define INCR4 instruction_1c
#define INCR5 instruction_1d
#define INCR6 instruction_1e
#define INCR7 instruction_1f
#define JMP1 instruction_24
#define CALL1 instruction_34
#define JMP2 instruction_44
#define CALL2 instruction_54
#define JMP3 instruction_64
#define CALL3 instruction_74
#define JMP4 instruction_84
#define CALL4 instruction_94
#define JMP5 instruction_a4
#define CALL5 instruction_b4
#define JMP6 instruction_c4
#define CALL6 instruction_d4
#define JMP7 instruction_e4
#define CALL7 instruction_f4
