#define NOP instruction_00
#define ADDI8 instruction_03
#define JMP0 instruction_04
#define ENI instruction_05
#define DECA instruction_07
#define IN1 instruction_09
#define IN2 instruction_0a
#define MOVDAP4 instruction_0c
#define MOVDAP5 instruction_0d
#define MOVDAP6 instruction_0e
#define MOVDAP7 instruction_0f
#define INCIR0 instruction_10
#define INCIR1 instruction_11
#define ADDCI8 instruction_13
#define CALL0 instruction_14
#define DISI instruction_15
#define INCA instruction_17
#define INCR0 instruction_18
#define INCR1 instruction_19
#define INCR2 instruction_1a
#define INCR3 instruction_1b
#define INCR4 instruction_1c
#define INCR5 instruction_1d
#define INCR6 instruction_1e
#define INCR7 instruction_1f
#define XCHAIR0 instruction_20
#define XCHAIR1 instruction_21
#define MOVAI8 instruction_23
#define JMP1 instruction_24
#define CLRA instruction_27
#define XCHAR0 instruction_28
#define XCHAR1 instruction_29
#define XCHAR2 instruction_2a
#define XCHAR3 instruction_2b
#define XCHAR4 instruction_2c
#define XCHAR5 instruction_2d
#define XCHAR6 instruction_2e
#define XCHAR7 instruction_2f
#define XCHDAIR0 instruction_30
#define XCHDAIR1 instruction_31
#define CALL1 instruction_34
#define CPLA instruction_37
#define MOVDP4A instruction_3c
#define MOVDP5A instruction_3d
#define MOVDP6A instruction_3e
#define MOVDP7A instruction_3f
#define ORLAIR0 instruction_40
#define ORLAIR1 instruction_41
#define JMP2 instruction_44
#define CALL2 instruction_54
#define JMP3 instruction_64
#define CALL3 instruction_74
#define JMP4 instruction_84
#define CALL4 instruction_94
#define JMP5 instruction_a4
#define CALL5 instruction_b4
#define JMP6 instruction_c4
#define CALL6 instruction_d4
#define JMP7 instruction_e4
#define CALL7 instruction_f4
