virtual int instruction_18_00(t_mem code){return resINV;}
virtual int instruction_18_01(t_mem code){return resINV;}
virtual int instruction_18_02(t_mem code){return resINV;}
virtual int instruction_18_03(t_mem code){return resINV;}
virtual int instruction_18_04(t_mem code){return resINV;}
virtual int instruction_18_05(t_mem code){return resINV;}
virtual int instruction_18_06(t_mem code){return resINV;}
virtual int instruction_18_07(t_mem code){return resINV;}
virtual int instruction_18_08(t_mem code){return resINV;}
virtual int instruction_18_09(t_mem code){return resINV;}
virtual int instruction_18_0a(t_mem code){return resINV;}
virtual int instruction_18_0b(t_mem code){return resINV;}
virtual int instruction_18_0c(t_mem code){return resINV;}
virtual int instruction_18_0d(t_mem code){return resINV;}
virtual int instruction_18_0e(t_mem code){return resINV;}
virtual int instruction_18_0f(t_mem code){return resINV;}
virtual int instruction_18_10(t_mem code){return resINV;}
virtual int instruction_18_11(t_mem code){return resINV;}
virtual int instruction_18_12(t_mem code){return resINV;}
virtual int instruction_18_13(t_mem code){return resINV;}
virtual int instruction_18_14(t_mem code){return resINV;}
virtual int instruction_18_15(t_mem code){return resINV;}
virtual int instruction_18_16(t_mem code){return resINV;}
virtual int instruction_18_17(t_mem code){return resINV;}
virtual int instruction_18_18(t_mem code){return resINV;}
virtual int instruction_18_19(t_mem code){return resINV;}
virtual int instruction_18_1a(t_mem code){return resINV;}
virtual int instruction_18_1b(t_mem code){return resINV;}
virtual int instruction_18_1c(t_mem code){return resINV;}
virtual int instruction_18_1d(t_mem code){return resINV;}
virtual int instruction_18_1e(t_mem code){return resINV;}
virtual int instruction_18_1f(t_mem code){return resINV;}
virtual int instruction_18_20(t_mem code){return resINV;}
virtual int instruction_18_21(t_mem code){return resINV;}
virtual int instruction_18_22(t_mem code){return resINV;}
virtual int instruction_18_23(t_mem code){return resINV;}
virtual int instruction_18_24(t_mem code){return resINV;}
virtual int instruction_18_25(t_mem code){return resINV;}
virtual int instruction_18_26(t_mem code){return resINV;}
virtual int instruction_18_27(t_mem code){return resINV;}
virtual int instruction_18_28(t_mem code){return resINV;}
virtual int instruction_18_29(t_mem code){return resINV;}
virtual int instruction_18_2a(t_mem code){return resINV;}
virtual int instruction_18_2b(t_mem code){return resINV;}
virtual int instruction_18_2c(t_mem code){return resINV;}
virtual int instruction_18_2d(t_mem code){return resINV;}
virtual int instruction_18_2e(t_mem code){return resINV;}
virtual int instruction_18_2f(t_mem code){return resINV;}
virtual int instruction_18_30(t_mem code){return resINV;}
virtual int instruction_18_31(t_mem code){return resINV;}
virtual int instruction_18_32(t_mem code){return resINV;}
virtual int instruction_18_33(t_mem code){return resINV;}
virtual int instruction_18_34(t_mem code){return resINV;}
virtual int instruction_18_35(t_mem code){return resINV;}
virtual int instruction_18_36(t_mem code){return resINV;}
virtual int instruction_18_37(t_mem code){return resINV;}
virtual int instruction_18_38(t_mem code){return resINV;}
virtual int instruction_18_39(t_mem code){return resINV;}
virtual int instruction_18_3a(t_mem code){return resINV;}
virtual int instruction_18_3b(t_mem code){return resINV;}
virtual int instruction_18_3c(t_mem code){return resINV;}
virtual int instruction_18_3d(t_mem code){return resINV;}
virtual int instruction_18_3e(t_mem code){return resINV;}
virtual int instruction_18_3f(t_mem code){return resINV;}
virtual int instruction_18_40(t_mem code){return resINV;}
virtual int instruction_18_41(t_mem code){return resINV;}
virtual int instruction_18_42(t_mem code){return resINV;}
virtual int instruction_18_43(t_mem code){return resINV;}
virtual int instruction_18_44(t_mem code){return resINV;}
virtual int instruction_18_45(t_mem code){return resINV;}
virtual int instruction_18_46(t_mem code){return resINV;}
virtual int instruction_18_47(t_mem code){return resINV;}
virtual int instruction_18_48(t_mem code){return resINV;}
virtual int instruction_18_49(t_mem code){return resINV;}
virtual int instruction_18_4a(t_mem code){return resINV;}
virtual int instruction_18_4b(t_mem code){return resINV;}
virtual int instruction_18_4c(t_mem code){return resINV;}
virtual int instruction_18_4d(t_mem code){return resINV;}
virtual int instruction_18_4e(t_mem code){return resINV;}
virtual int instruction_18_4f(t_mem code){return resINV;}
virtual int instruction_18_50(t_mem code){return resINV;}
virtual int instruction_18_51(t_mem code){return resINV;}
virtual int instruction_18_52(t_mem code){return resINV;}
virtual int instruction_18_53(t_mem code){return resINV;}
virtual int instruction_18_54(t_mem code){return resINV;}
virtual int instruction_18_55(t_mem code){return resINV;}
virtual int instruction_18_56(t_mem code){return resINV;}
virtual int instruction_18_57(t_mem code){return resINV;}
virtual int instruction_18_58(t_mem code){return resINV;}
virtual int instruction_18_59(t_mem code){return resINV;}
virtual int instruction_18_5a(t_mem code){return resINV;}
virtual int instruction_18_5b(t_mem code){return resINV;}
virtual int instruction_18_5c(t_mem code){return resINV;}
virtual int instruction_18_5d(t_mem code){return resINV;}
virtual int instruction_18_5e(t_mem code){return resINV;}
virtual int instruction_18_5f(t_mem code){return resINV;}
virtual int instruction_18_60(t_mem code){return resINV;}
virtual int instruction_18_61(t_mem code){return resINV;}
virtual int instruction_18_62(t_mem code){return resINV;}
virtual int instruction_18_63(t_mem code){return resINV;}
virtual int instruction_18_64(t_mem code){return resINV;}
virtual int instruction_18_65(t_mem code){return resINV;}
virtual int instruction_18_66(t_mem code){return resINV;}
virtual int instruction_18_67(t_mem code){return resINV;}
virtual int instruction_18_68(t_mem code){return resINV;}
virtual int instruction_18_69(t_mem code){return resINV;}
virtual int instruction_18_6a(t_mem code){return resINV;}
virtual int instruction_18_6b(t_mem code){return resINV;}
virtual int instruction_18_6c(t_mem code){return resINV;}
virtual int instruction_18_6d(t_mem code){return resINV;}
virtual int instruction_18_6e(t_mem code){return resINV;}
virtual int instruction_18_6f(t_mem code){return resINV;}
virtual int instruction_18_70(t_mem code){return resINV;}
virtual int instruction_18_71(t_mem code){return resINV;}
virtual int instruction_18_72(t_mem code){return resINV;}
virtual int instruction_18_73(t_mem code){return resINV;}
virtual int instruction_18_74(t_mem code){return resINV;}
virtual int instruction_18_75(t_mem code){return resINV;}
virtual int instruction_18_76(t_mem code){return resINV;}
virtual int instruction_18_77(t_mem code){return resINV;}
virtual int instruction_18_78(t_mem code){return resINV;}
virtual int instruction_18_79(t_mem code){return resINV;}
virtual int instruction_18_7a(t_mem code){return resINV;}
virtual int instruction_18_7b(t_mem code){return resINV;}
virtual int instruction_18_7c(t_mem code){return resINV;}
virtual int instruction_18_7d(t_mem code){return resINV;}
virtual int instruction_18_7e(t_mem code){return resINV;}
virtual int instruction_18_7f(t_mem code){return resINV;}
virtual int instruction_18_80(t_mem code){return resINV;}
virtual int instruction_18_81(t_mem code){return resINV;}
virtual int instruction_18_82(t_mem code){return resINV;}
virtual int instruction_18_83(t_mem code){return resINV;}
virtual int instruction_18_84(t_mem code){return resINV;}
virtual int instruction_18_85(t_mem code){return resINV;}
virtual int instruction_18_86(t_mem code){return resINV;}
virtual int instruction_18_87(t_mem code){return resINV;}
virtual int instruction_18_88(t_mem code){return resINV;}
virtual int instruction_18_89(t_mem code){return resINV;}
virtual int instruction_18_8a(t_mem code){return resINV;}
virtual int instruction_18_8b(t_mem code){return resINV;}
virtual int instruction_18_8c(t_mem code){return resINV;}
virtual int instruction_18_8d(t_mem code){return resINV;}
virtual int instruction_18_8e(t_mem code){return resINV;}
virtual int instruction_18_8f(t_mem code){return resINV;}
virtual int instruction_18_90(t_mem code){return resINV;}
virtual int instruction_18_91(t_mem code){return resINV;}
virtual int instruction_18_92(t_mem code){return resINV;}
virtual int instruction_18_93(t_mem code){return resINV;}
virtual int instruction_18_94(t_mem code){return resINV;}
virtual int instruction_18_95(t_mem code){return resINV;}
virtual int instruction_18_96(t_mem code){return resINV;}
virtual int instruction_18_97(t_mem code){return resINV;}
virtual int instruction_18_98(t_mem code){return resINV;}
virtual int instruction_18_99(t_mem code){return resINV;}
virtual int instruction_18_9a(t_mem code){return resINV;}
virtual int instruction_18_9b(t_mem code){return resINV;}
virtual int instruction_18_9c(t_mem code){return resINV;}
virtual int instruction_18_9d(t_mem code){return resINV;}
virtual int instruction_18_9e(t_mem code){return resINV;}
virtual int instruction_18_9f(t_mem code){return resINV;}
virtual int instruction_18_a0(t_mem code){return resINV;}
virtual int instruction_18_a1(t_mem code){return resINV;}
virtual int instruction_18_a2(t_mem code){return resINV;}
virtual int instruction_18_a3(t_mem code){return resINV;}
virtual int instruction_18_a4(t_mem code){return resINV;}
virtual int instruction_18_a5(t_mem code){return resINV;}
virtual int instruction_18_a6(t_mem code){return resINV;}
virtual int instruction_18_a7(t_mem code){return resINV;}
virtual int instruction_18_a8(t_mem code){return resINV;}
virtual int instruction_18_a9(t_mem code){return resINV;}
virtual int instruction_18_aa(t_mem code){return resINV;}
virtual int instruction_18_ab(t_mem code){return resINV;}
virtual int instruction_18_ac(t_mem code){return resINV;}
virtual int instruction_18_ad(t_mem code){return resINV;}
virtual int instruction_18_ae(t_mem code){return resINV;}
virtual int instruction_18_af(t_mem code){return resINV;}
virtual int instruction_18_b0(t_mem code){return resINV;}
virtual int instruction_18_b1(t_mem code){return resINV;}
virtual int instruction_18_b2(t_mem code){return resINV;}
virtual int instruction_18_b3(t_mem code){return resINV;}
virtual int instruction_18_b4(t_mem code){return resINV;}
virtual int instruction_18_b5(t_mem code){return resINV;}
virtual int instruction_18_b6(t_mem code){return resINV;}
virtual int instruction_18_b7(t_mem code){return resINV;}
virtual int instruction_18_b8(t_mem code){return resINV;}
virtual int instruction_18_b9(t_mem code){return resINV;}
virtual int instruction_18_ba(t_mem code){return resINV;}
virtual int instruction_18_bb(t_mem code){return resINV;}
virtual int instruction_18_bc(t_mem code){return resINV;}
virtual int instruction_18_bd(t_mem code){return resINV;}
virtual int instruction_18_be(t_mem code){return resINV;}
virtual int instruction_18_bf(t_mem code){return resINV;}
virtual int instruction_18_c0(t_mem code){return resINV;}
virtual int instruction_18_c1(t_mem code){return resINV;}
virtual int instruction_18_c2(t_mem code){return resINV;}
virtual int instruction_18_c3(t_mem code){return resINV;}
virtual int instruction_18_c4(t_mem code){return resINV;}
virtual int instruction_18_c5(t_mem code){return resINV;}
virtual int instruction_18_c6(t_mem code){return resINV;}
virtual int instruction_18_c7(t_mem code){return resINV;}
virtual int instruction_18_c8(t_mem code){return resINV;}
virtual int instruction_18_c9(t_mem code){return resINV;}
virtual int instruction_18_ca(t_mem code){return resINV;}
virtual int instruction_18_cb(t_mem code){return resINV;}
virtual int instruction_18_cc(t_mem code){return resINV;}
virtual int instruction_18_cd(t_mem code){return resINV;}
virtual int instruction_18_ce(t_mem code){return resINV;}
virtual int instruction_18_cf(t_mem code){return resINV;}
virtual int instruction_18_d0(t_mem code){return resINV;}
virtual int instruction_18_d1(t_mem code){return resINV;}
virtual int instruction_18_d2(t_mem code){return resINV;}
virtual int instruction_18_d3(t_mem code){return resINV;}
virtual int instruction_18_d4(t_mem code){return resINV;}
virtual int instruction_18_d5(t_mem code){return resINV;}
virtual int instruction_18_d6(t_mem code){return resINV;}
virtual int instruction_18_d7(t_mem code){return resINV;}
virtual int instruction_18_d8(t_mem code){return resINV;}
virtual int instruction_18_d9(t_mem code){return resINV;}
virtual int instruction_18_da(t_mem code){return resINV;}
virtual int instruction_18_db(t_mem code){return resINV;}
virtual int instruction_18_dc(t_mem code){return resINV;}
virtual int instruction_18_dd(t_mem code){return resINV;}
virtual int instruction_18_de(t_mem code){return resINV;}
virtual int instruction_18_df(t_mem code){return resINV;}
virtual int instruction_18_e0(t_mem code){return resINV;}
virtual int instruction_18_e1(t_mem code){return resINV;}
virtual int instruction_18_e2(t_mem code){return resINV;}
virtual int instruction_18_e3(t_mem code){return resINV;}
virtual int instruction_18_e4(t_mem code){return resINV;}
virtual int instruction_18_e5(t_mem code){return resINV;}
virtual int instruction_18_e6(t_mem code){return resINV;}
virtual int instruction_18_e7(t_mem code){return resINV;}
virtual int instruction_18_e8(t_mem code){return resINV;}
virtual int instruction_18_e9(t_mem code){return resINV;}
virtual int instruction_18_ea(t_mem code){return resINV;}
virtual int instruction_18_eb(t_mem code){return resINV;}
virtual int instruction_18_ec(t_mem code){return resINV;}
virtual int instruction_18_ed(t_mem code){return resINV;}
virtual int instruction_18_ee(t_mem code){return resINV;}
virtual int instruction_18_ef(t_mem code){return resINV;}
virtual int instruction_18_f0(t_mem code){return resINV;}
virtual int instruction_18_f1(t_mem code){return resINV;}
virtual int instruction_18_f2(t_mem code){return resINV;}
virtual int instruction_18_f3(t_mem code){return resINV;}
virtual int instruction_18_f4(t_mem code){return resINV;}
virtual int instruction_18_f5(t_mem code){return resINV;}
virtual int instruction_18_f6(t_mem code){return resINV;}
virtual int instruction_18_f7(t_mem code){return resINV;}
virtual int instruction_18_f8(t_mem code){return resINV;}
virtual int instruction_18_f9(t_mem code){return resINV;}
virtual int instruction_18_fa(t_mem code){return resINV;}
virtual int instruction_18_fb(t_mem code){return resINV;}
virtual int instruction_18_fc(t_mem code){return resINV;}
virtual int instruction_18_fd(t_mem code){return resINV;}
virtual int instruction_18_fe(t_mem code){return resINV;}
virtual int instruction_18_ff(t_mem code){return resINV;}
