virtual int instruction_hc_00(t_mem code){return resINV;}
virtual int instruction_hc_01(t_mem code){return resINV;}
virtual int instruction_hc_02(t_mem code){return resINV;}
virtual int instruction_hc_03(t_mem code){return resINV;}
virtual int instruction_hc_04(t_mem code){return resINV;}
virtual int instruction_hc_05(t_mem code){return resINV;}
virtual int instruction_hc_06(t_mem code){return resINV;}
virtual int instruction_hc_07(t_mem code){return resINV;}
virtual int instruction_hc_08(t_mem code){return resINV;}
virtual int instruction_hc_09(t_mem code){return resINV;}
virtual int instruction_hc_0a(t_mem code){return resINV;}
virtual int instruction_hc_0b(t_mem code){return resINV;}
virtual int instruction_hc_0c(t_mem code){return resINV;}
virtual int instruction_hc_0d(t_mem code){return resINV;}
virtual int instruction_hc_0e(t_mem code){return resINV;}
virtual int instruction_hc_0f(t_mem code){return resINV;}
virtual int instruction_hc_10(t_mem code){return resINV;}
virtual int instruction_hc_11(t_mem code){return resINV;}
virtual int instruction_hc_12(t_mem code){return resINV;}
virtual int instruction_hc_13(t_mem code){return resINV;}
virtual int instruction_hc_14(t_mem code){return resINV;}
virtual int instruction_hc_15(t_mem code){return resINV;}
virtual int instruction_hc_16(t_mem code){return resINV;}
virtual int instruction_hc_17(t_mem code){return resINV;}
virtual int instruction_hc_18(t_mem code){return resINV;}
virtual int instruction_hc_19(t_mem code){return resINV;}
virtual int instruction_hc_1a(t_mem code){return resINV;}
virtual int instruction_hc_1b(t_mem code){return resINV;}
virtual int instruction_hc_1c(t_mem code){return resINV;}
virtual int instruction_hc_1d(t_mem code){return resINV;}
virtual int instruction_hc_1e(t_mem code){return resINV;}
virtual int instruction_hc_1f(t_mem code){return resINV;}
virtual int instruction_hc_20(t_mem code){return resINV;}
virtual int instruction_hc_21(t_mem code){return resINV;}
virtual int instruction_hc_22(t_mem code){return resINV;}
virtual int instruction_hc_23(t_mem code){return resINV;}
virtual int instruction_hc_24(t_mem code){return resINV;}
virtual int instruction_hc_25(t_mem code){return resINV;}
virtual int instruction_hc_26(t_mem code){return resINV;}
virtual int instruction_hc_27(t_mem code){return resINV;}
virtual int instruction_hc_28(t_mem code){return resINV;}
virtual int instruction_hc_29(t_mem code){return resINV;}
virtual int instruction_hc_2a(t_mem code){return resINV;}
virtual int instruction_hc_2b(t_mem code){return resINV;}
virtual int instruction_hc_2c(t_mem code){return resINV;}
virtual int instruction_hc_2d(t_mem code){return resINV;}
virtual int instruction_hc_2e(t_mem code){return resINV;}
virtual int instruction_hc_2f(t_mem code){return resINV;}
virtual int instruction_hc_30(t_mem code){return resINV;}
virtual int instruction_hc_31(t_mem code){return resINV;}
virtual int instruction_hc_32(t_mem code){return resINV;}
virtual int instruction_hc_33(t_mem code){return resINV;}
virtual int instruction_hc_34(t_mem code){return resINV;}
virtual int instruction_hc_35(t_mem code){return resINV;}
virtual int instruction_hc_36(t_mem code){return resINV;}
virtual int instruction_hc_37(t_mem code){return resINV;}
virtual int instruction_hc_38(t_mem code){return resINV;}
virtual int instruction_hc_39(t_mem code){return resINV;}
virtual int instruction_hc_3a(t_mem code){return resINV;}
virtual int instruction_hc_3b(t_mem code){return resINV;}
virtual int instruction_hc_3c(t_mem code){return resINV;}
virtual int instruction_hc_3d(t_mem code){return resINV;}
virtual int instruction_hc_3e(t_mem code){return resINV;}
virtual int instruction_hc_3f(t_mem code){return resINV;}
virtual int instruction_hc_40(t_mem code){return resINV;}
virtual int instruction_hc_41(t_mem code){return resINV;}
virtual int instruction_hc_42(t_mem code){return resINV;}
virtual int instruction_hc_43(t_mem code){return resINV;}
virtual int instruction_hc_44(t_mem code){return resINV;}
virtual int instruction_hc_45(t_mem code){return resINV;}
virtual int instruction_hc_46(t_mem code){return resINV;}
virtual int instruction_hc_47(t_mem code){return resINV;}
virtual int instruction_hc_48(t_mem code){return resINV;}
virtual int instruction_hc_49(t_mem code){return resINV;}
virtual int instruction_hc_4a(t_mem code){return resINV;}
virtual int instruction_hc_4b(t_mem code){return resINV;}
virtual int instruction_hc_4c(t_mem code){return resINV;}
virtual int instruction_hc_4d(t_mem code){return resINV;}
virtual int instruction_hc_4e(t_mem code){return resINV;}
virtual int instruction_hc_4f(t_mem code){return resINV;}
virtual int instruction_hc_50(t_mem code){return resINV;}
virtual int instruction_hc_51(t_mem code){return resINV;}
virtual int instruction_hc_52(t_mem code){return resINV;}
virtual int instruction_hc_53(t_mem code){return resINV;}
virtual int instruction_hc_54(t_mem code){return resINV;}
virtual int instruction_hc_55(t_mem code){return resINV;}
virtual int instruction_hc_56(t_mem code){return resINV;}
virtual int instruction_hc_57(t_mem code){return resINV;}
virtual int instruction_hc_58(t_mem code){return resINV;}
virtual int instruction_hc_59(t_mem code){return resINV;}
virtual int instruction_hc_5a(t_mem code){return resINV;}
virtual int instruction_hc_5b(t_mem code){return resINV;}
virtual int instruction_hc_5c(t_mem code){return resINV;}
virtual int instruction_hc_5d(t_mem code){return resINV;}
virtual int instruction_hc_5e(t_mem code){return resINV;}
virtual int instruction_hc_5f(t_mem code){return resINV;}
virtual int instruction_hc_60(t_mem code){return resINV;}
virtual int instruction_hc_61(t_mem code){return resINV;}
virtual int instruction_hc_62(t_mem code){return resINV;}
virtual int instruction_hc_63(t_mem code){return resINV;}
virtual int instruction_hc_64(t_mem code){return resINV;}
virtual int instruction_hc_65(t_mem code){return resINV;}
virtual int instruction_hc_66(t_mem code){return resINV;}
virtual int instruction_hc_67(t_mem code){return resINV;}
virtual int instruction_hc_68(t_mem code){return resINV;}
virtual int instruction_hc_69(t_mem code){return resINV;}
virtual int instruction_hc_6a(t_mem code){return resINV;}
virtual int instruction_hc_6b(t_mem code){return resINV;}
virtual int instruction_hc_6c(t_mem code){return resINV;}
virtual int instruction_hc_6d(t_mem code){return resINV;}
virtual int instruction_hc_6e(t_mem code){return resINV;}
virtual int instruction_hc_6f(t_mem code){return resINV;}
virtual int instruction_hc_70(t_mem code){return resINV;}
virtual int instruction_hc_71(t_mem code){return resINV;}
virtual int instruction_hc_72(t_mem code){return resINV;}
virtual int instruction_hc_73(t_mem code){return resINV;}
virtual int instruction_hc_74(t_mem code){return resINV;}
virtual int instruction_hc_75(t_mem code){return resINV;}
virtual int instruction_hc_76(t_mem code){return resINV;}
virtual int instruction_hc_77(t_mem code){return resINV;}
virtual int instruction_hc_78(t_mem code){return resINV;}
virtual int instruction_hc_79(t_mem code){return resINV;}
virtual int instruction_hc_7a(t_mem code){return resINV;}
virtual int instruction_hc_7b(t_mem code){return resINV;}
virtual int instruction_hc_7c(t_mem code){return resINV;}
virtual int instruction_hc_7d(t_mem code){return resINV;}
virtual int instruction_hc_7e(t_mem code){return resINV;}
virtual int instruction_hc_7f(t_mem code){return resINV;}
virtual int instruction_hc_80(t_mem code){return resINV;}
virtual int instruction_hc_81(t_mem code){return resINV;}
virtual int instruction_hc_82(t_mem code){return resINV;}
virtual int instruction_hc_83(t_mem code){return resINV;}
virtual int instruction_hc_84(t_mem code){return resINV;}
virtual int instruction_hc_85(t_mem code){return resINV;}
virtual int instruction_hc_86(t_mem code){return resINV;}
virtual int instruction_hc_87(t_mem code){return resINV;}
virtual int instruction_hc_88(t_mem code){return resINV;}
virtual int instruction_hc_89(t_mem code){return resINV;}
virtual int instruction_hc_8a(t_mem code){return resINV;}
virtual int instruction_hc_8b(t_mem code){return resINV;}
virtual int instruction_hc_8c(t_mem code){return resINV;}
virtual int instruction_hc_8d(t_mem code){return resINV;}
virtual int instruction_hc_8e(t_mem code){return resINV;}
virtual int instruction_hc_8f(t_mem code){return resINV;}
virtual int instruction_hc_90(t_mem code){return resINV;}
virtual int instruction_hc_91(t_mem code){return resINV;}
virtual int instruction_hc_92(t_mem code){return resINV;}
virtual int instruction_hc_93(t_mem code){return resINV;}
virtual int instruction_hc_94(t_mem code){return resINV;}
virtual int instruction_hc_95(t_mem code){return resINV;}
virtual int instruction_hc_96(t_mem code){return resINV;}
virtual int instruction_hc_97(t_mem code){return resINV;}
virtual int instruction_hc_98(t_mem code){return resINV;}
virtual int instruction_hc_99(t_mem code){return resINV;}
virtual int instruction_hc_9a(t_mem code){return resINV;}
virtual int instruction_hc_9b(t_mem code){return resINV;}
virtual int instruction_hc_9c(t_mem code){return resINV;}
virtual int instruction_hc_9d(t_mem code){return resINV;}
virtual int instruction_hc_9e(t_mem code){return resINV;}
virtual int instruction_hc_9f(t_mem code){return resINV;}
virtual int instruction_hc_a0(t_mem code){return resINV;}
virtual int instruction_hc_a1(t_mem code){return resINV;}
virtual int instruction_hc_a2(t_mem code){return resINV;}
virtual int instruction_hc_a3(t_mem code){return resINV;}
virtual int instruction_hc_a4(t_mem code){return resINV;}
virtual int instruction_hc_a5(t_mem code){return resINV;}
virtual int instruction_hc_a6(t_mem code){return resINV;}
virtual int instruction_hc_a7(t_mem code){return resINV;}
virtual int instruction_hc_a8(t_mem code){return resINV;}
virtual int instruction_hc_a9(t_mem code){return resINV;}
virtual int instruction_hc_aa(t_mem code){return resINV;}
virtual int instruction_hc_ab(t_mem code){return resINV;}
virtual int instruction_hc_ac(t_mem code){return resINV;}
virtual int instruction_hc_ad(t_mem code){return resINV;}
virtual int instruction_hc_ae(t_mem code){return resINV;}
virtual int instruction_hc_af(t_mem code){return resINV;}
virtual int instruction_hc_b0(t_mem code){return resINV;}
virtual int instruction_hc_b1(t_mem code){return resINV;}
virtual int instruction_hc_b2(t_mem code){return resINV;}
virtual int instruction_hc_b3(t_mem code){return resINV;}
virtual int instruction_hc_b4(t_mem code){return resINV;}
virtual int instruction_hc_b5(t_mem code){return resINV;}
virtual int instruction_hc_b6(t_mem code){return resINV;}
virtual int instruction_hc_b7(t_mem code){return resINV;}
virtual int instruction_hc_b8(t_mem code){return resINV;}
virtual int instruction_hc_b9(t_mem code){return resINV;}
virtual int instruction_hc_ba(t_mem code){return resINV;}
virtual int instruction_hc_bb(t_mem code){return resINV;}
virtual int instruction_hc_bc(t_mem code){return resINV;}
virtual int instruction_hc_bd(t_mem code){return resINV;}
virtual int instruction_hc_be(t_mem code){return resINV;}
virtual int instruction_hc_bf(t_mem code){return resINV;}
virtual int instruction_hc_c0(t_mem code){return resINV;}
virtual int instruction_hc_c1(t_mem code){return resINV;}
virtual int instruction_hc_c2(t_mem code){return resINV;}
virtual int instruction_hc_c3(t_mem code){return resINV;}
virtual int instruction_hc_c4(t_mem code){return resINV;}
virtual int instruction_hc_c5(t_mem code){return resINV;}
virtual int instruction_hc_c6(t_mem code){return resINV;}
virtual int instruction_hc_c7(t_mem code){return resINV;}
virtual int instruction_hc_c8(t_mem code){return resINV;}
virtual int instruction_hc_c9(t_mem code){return resINV;}
virtual int instruction_hc_ca(t_mem code){return resINV;}
virtual int instruction_hc_cb(t_mem code){return resINV;}
virtual int instruction_hc_cc(t_mem code){return resINV;}
virtual int instruction_hc_cd(t_mem code){return resINV;}
virtual int instruction_hc_ce(t_mem code){return resINV;}
virtual int instruction_hc_cf(t_mem code){return resINV;}
virtual int instruction_hc_d0(t_mem code){return resINV;}
virtual int instruction_hc_d1(t_mem code){return resINV;}
virtual int instruction_hc_d2(t_mem code){return resINV;}
virtual int instruction_hc_d3(t_mem code){return resINV;}
virtual int instruction_hc_d4(t_mem code){return resINV;}
virtual int instruction_hc_d5(t_mem code){return resINV;}
virtual int instruction_hc_d6(t_mem code){return resINV;}
virtual int instruction_hc_d7(t_mem code){return resINV;}
virtual int instruction_hc_d8(t_mem code){return resINV;}
virtual int instruction_hc_d9(t_mem code){return resINV;}
virtual int instruction_hc_da(t_mem code){return resINV;}
virtual int instruction_hc_db(t_mem code){return resINV;}
virtual int instruction_hc_dc(t_mem code){return resINV;}
virtual int instruction_hc_dd(t_mem code){return resINV;}
virtual int instruction_hc_de(t_mem code){return resINV;}
virtual int instruction_hc_df(t_mem code){return resINV;}
virtual int instruction_hc_e0(t_mem code){return resINV;}
virtual int instruction_hc_e1(t_mem code){return resINV;}
virtual int instruction_hc_e2(t_mem code){return resINV;}
virtual int instruction_hc_e3(t_mem code){return resINV;}
virtual int instruction_hc_e4(t_mem code){return resINV;}
virtual int instruction_hc_e5(t_mem code){return resINV;}
virtual int instruction_hc_e6(t_mem code){return resINV;}
virtual int instruction_hc_e7(t_mem code){return resINV;}
virtual int instruction_hc_e8(t_mem code){return resINV;}
virtual int instruction_hc_e9(t_mem code){return resINV;}
virtual int instruction_hc_ea(t_mem code){return resINV;}
virtual int instruction_hc_eb(t_mem code){return resINV;}
virtual int instruction_hc_ec(t_mem code){return resINV;}
virtual int instruction_hc_ed(t_mem code){return resINV;}
virtual int instruction_hc_ee(t_mem code){return resINV;}
virtual int instruction_hc_ef(t_mem code){return resINV;}
virtual int instruction_hc_f0(t_mem code){return resINV;}
virtual int instruction_hc_f1(t_mem code){return resINV;}
virtual int instruction_hc_f2(t_mem code){return resINV;}
virtual int instruction_hc_f3(t_mem code){return resINV;}
virtual int instruction_hc_f4(t_mem code){return resINV;}
virtual int instruction_hc_f5(t_mem code){return resINV;}
virtual int instruction_hc_f6(t_mem code){return resINV;}
virtual int instruction_hc_f7(t_mem code){return resINV;}
virtual int instruction_hc_f8(t_mem code){return resINV;}
virtual int instruction_hc_f9(t_mem code){return resINV;}
virtual int instruction_hc_fa(t_mem code){return resINV;}
virtual int instruction_hc_fb(t_mem code){return resINV;}
virtual int instruction_hc_fc(t_mem code){return resINV;}
virtual int instruction_hc_fd(t_mem code){return resINV;}
virtual int instruction_hc_fe(t_mem code){return resINV;}
virtual int instruction_hc_ff(t_mem code){return resINV;}
