 int wrap_0_89(class CL12 *uc, t_mem code) { return uc-> adc ( _A_i8 ); } 
 int wrap_0_99(class CL12 *uc, t_mem code) { return uc-> adc ( _A_dop ); } 
 int wrap_0_a9(class CL12 *uc, t_mem code) { return uc-> adc ( _A_xbop8 ); } 
 int wrap_0_b9(class CL12 *uc, t_mem code) { return uc-> adc ( _A_eop ); } 
 int wrap_0_c9(class CL12 *uc, t_mem code) { return uc-> adc ( _B_i8 ); } 
 int wrap_0_d9(class CL12 *uc, t_mem code) { return uc-> adc ( _B_dop ); } 
 int wrap_0_e9(class CL12 *uc, t_mem code) { return uc-> adc ( _B_xbop8 ); } 
 int wrap_0_f9(class CL12 *uc, t_mem code) { return uc-> adc ( _B_eop ); } 
 int wrap_0_8b(class CL12 *uc, t_mem code) { return uc-> add ( _A_i8 ); } 
 int wrap_0_9b(class CL12 *uc, t_mem code) { return uc-> add ( _A_dop ); } 
 int wrap_0_ab(class CL12 *uc, t_mem code) { return uc-> add ( _A_xbop8 ); } 
 int wrap_0_bb(class CL12 *uc, t_mem code) { return uc-> add ( _A_eop ); } 
 int wrap_0_cb(class CL12 *uc, t_mem code) { return uc-> add ( _B_i8 ); } 
 int wrap_0_db(class CL12 *uc, t_mem code) { return uc-> add ( _B_dop ); } 
 int wrap_0_eb(class CL12 *uc, t_mem code) { return uc-> add ( _B_xbop8 ); } 
 int wrap_0_fb(class CL12 *uc, t_mem code) { return uc-> add ( _B_eop ); } 
 int wrap_0_84(class CL12 *uc, t_mem code) { return uc-> And ( _A_i8 ); } 
 int wrap_0_94(class CL12 *uc, t_mem code) { return uc-> And ( _A_dop ); } 
 int wrap_0_a4(class CL12 *uc, t_mem code) { return uc-> And ( _A_xbop8 ); } 
 int wrap_0_b4(class CL12 *uc, t_mem code) { return uc-> And ( _A_eop ); } 
 int wrap_0_c4(class CL12 *uc, t_mem code) { return uc-> And ( _B_i8 ); } 
 int wrap_0_d4(class CL12 *uc, t_mem code) { return uc-> And ( _B_dop ); } 
 int wrap_0_e4(class CL12 *uc, t_mem code) { return uc-> And ( _B_xbop8 ); } 
 int wrap_0_f4(class CL12 *uc, t_mem code) { return uc-> And ( _B_eop ); } 
 int wrap_0_88(class CL12 *uc, t_mem code) { return uc-> eor ( _A_i8 ); } 
 int wrap_0_98(class CL12 *uc, t_mem code) { return uc-> eor ( _A_dop ); } 
 int wrap_0_a8(class CL12 *uc, t_mem code) { return uc-> eor ( _A_xbop8 ); } 
 int wrap_0_b8(class CL12 *uc, t_mem code) { return uc-> eor ( _A_eop ); } 
 int wrap_0_c8(class CL12 *uc, t_mem code) { return uc-> eor ( _B_i8 ); } 
 int wrap_0_d8(class CL12 *uc, t_mem code) { return uc-> eor ( _B_dop ); } 
 int wrap_0_e8(class CL12 *uc, t_mem code) { return uc-> eor ( _B_xbop8 ); } 
 int wrap_0_f8(class CL12 *uc, t_mem code) { return uc-> eor ( _B_eop ); } 
 int wrap_0_8a(class CL12 *uc, t_mem code) { return uc-> Or ( _A_i8 ); } 
 int wrap_0_9a(class CL12 *uc, t_mem code) { return uc-> Or ( _A_dop ); } 
 int wrap_0_aa(class CL12 *uc, t_mem code) { return uc-> Or ( _A_xbop8 ); } 
 int wrap_0_ba(class CL12 *uc, t_mem code) { return uc-> Or ( _A_eop ); } 
 int wrap_0_ca(class CL12 *uc, t_mem code) { return uc-> Or ( _B_i8 ); } 
 int wrap_0_da(class CL12 *uc, t_mem code) { return uc-> Or ( _B_dop ); } 
 int wrap_0_ea(class CL12 *uc, t_mem code) { return uc-> Or ( _B_xbop8 ); } 
 int wrap_0_fa(class CL12 *uc, t_mem code) { return uc-> Or ( _B_eop ); } 
 int wrap_0_85(class CL12 *uc, t_mem code) { return uc-> bit ( _Aop_i8 ); } 
 int wrap_0_95(class CL12 *uc, t_mem code) { return uc-> bit ( _Aop_dop ); } 
 int wrap_0_a5(class CL12 *uc, t_mem code) { return uc-> bit ( _Aop_xbop8 ); } 
 int wrap_0_b5(class CL12 *uc, t_mem code) { return uc-> bit ( _Aop_eop ); } 
 int wrap_0_c5(class CL12 *uc, t_mem code) { return uc-> bit ( _Bop_i8 ); } 
 int wrap_0_d5(class CL12 *uc, t_mem code) { return uc-> bit ( _Bop_dop ); } 
 int wrap_0_e5(class CL12 *uc, t_mem code) { return uc-> bit ( _Bop_xbop8 ); } 
 int wrap_0_f5(class CL12 *uc, t_mem code) { return uc-> bit ( _Bop_eop ); } 
 int wrap_0_81(class CL12 *uc, t_mem code) { return uc-> cmp ( _Aop_i8 ); } 
 int wrap_0_91(class CL12 *uc, t_mem code) { return uc-> cmp ( _Aop_dop ); } 
 int wrap_0_a1(class CL12 *uc, t_mem code) { return uc-> cmp ( _Aop_xbop8 ); } 
 int wrap_0_b1(class CL12 *uc, t_mem code) { return uc-> cmp ( _Aop_eop ); } 
 int wrap_0_c1(class CL12 *uc, t_mem code) { return uc-> cmp ( _Bop_i8 ); } 
 int wrap_0_d1(class CL12 *uc, t_mem code) { return uc-> cmp ( _Bop_dop ); } 
 int wrap_0_e1(class CL12 *uc, t_mem code) { return uc-> cmp ( _Bop_xbop8 ); } 
 int wrap_0_f1(class CL12 *uc, t_mem code) { return uc-> cmp ( _Bop_eop ); } 
 int wrap_0_80(class CL12 *uc, t_mem code) { return uc-> sub ( _A_i8 ); } 
 int wrap_0_90(class CL12 *uc, t_mem code) { return uc-> sub ( _A_dop ); } 
 int wrap_0_a0(class CL12 *uc, t_mem code) { return uc-> sub ( _A_xbop8 ); } 
 int wrap_0_b0(class CL12 *uc, t_mem code) { return uc-> sub ( _A_eop ); } 
 int wrap_0_c0(class CL12 *uc, t_mem code) { return uc-> sub ( _B_i8 ); } 
 int wrap_0_d0(class CL12 *uc, t_mem code) { return uc-> sub ( _B_dop ); } 
 int wrap_0_e0(class CL12 *uc, t_mem code) { return uc-> sub ( _B_xbop8 ); } 
 int wrap_0_f0(class CL12 *uc, t_mem code) { return uc-> sub ( _B_eop ); } 
 int wrap_0_82(class CL12 *uc, t_mem code) { return uc-> sbc ( _A_i8 ); } 
 int wrap_0_92(class CL12 *uc, t_mem code) { return uc-> sbc ( _A_dop ); } 
 int wrap_0_a2(class CL12 *uc, t_mem code) { return uc-> sbc ( _A_xbop8 ); } 
 int wrap_0_b2(class CL12 *uc, t_mem code) { return uc-> sbc ( _A_eop ); } 
 int wrap_0_c2(class CL12 *uc, t_mem code) { return uc-> sbc ( _B_i8 ); } 
 int wrap_0_d2(class CL12 *uc, t_mem code) { return uc-> sbc ( _B_dop ); } 
 int wrap_0_e2(class CL12 *uc, t_mem code) { return uc-> sbc ( _B_xbop8 ); } 
 int wrap_0_f2(class CL12 *uc, t_mem code) { return uc-> sbc ( _B_eop ); } 
 int wrap_0_86(class CL12 *uc, t_mem code) { return uc-> lda ( _A_i8 ); } 
 int wrap_0_96(class CL12 *uc, t_mem code) { return uc-> lda ( _A_dop ); } 
 int wrap_0_a6(class CL12 *uc, t_mem code) { return uc-> lda ( _A_xbop8 ); } 
 int wrap_0_b6(class CL12 *uc, t_mem code) { return uc-> lda ( _A_eop ); } 
 int wrap_0_c6(class CL12 *uc, t_mem code) { return uc-> lda ( _B_i8 ); } 
 int wrap_0_d6(class CL12 *uc, t_mem code) { return uc-> lda ( _B_dop ); } 
 int wrap_0_e6(class CL12 *uc, t_mem code) { return uc-> lda ( _B_xbop8 ); } 
 int wrap_0_f6(class CL12 *uc, t_mem code) { return uc-> lda ( _B_eop ); } 
 int wrap_0_83(class CL12 *uc, t_mem code) { return uc-> sub16 ( _D_i16 ); } 
 int wrap_0_93(class CL12 *uc, t_mem code) { return uc-> sub16 ( _D_dop16 ); } 
 int wrap_0_a3(class CL12 *uc, t_mem code) { return uc-> sub16 ( _D_xbop16 ); } 
 int wrap_0_b3(class CL12 *uc, t_mem code) { return uc-> sub16 ( _D_eop16 ); } 
 int wrap_0_b7(class CL12 *uc, t_mem code) { return uc-> exec_b7 ( _NONE ); } 
 int wrap_0x18_06(class CL12 *uc, t_mem code) { return uc-> add ( _A_B ); } 
