/*
 * Simulator of microcontrollers (decode.h)
 *
 * Copyright (C) 2022 Drotos Daniel
 * 
 * To contact author send email to dr.dkdb@gmail.com
 *
 */

/* This file is part of microcontroller simulator: ucsim.

UCSIM is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

UCSIM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with UCSIM; see the file COPYING.  If not, write to the Free
Software Foundation, 59 Temple Place - Suite 330, Boston, MA
02111-1307, USA. */
/*@1@*/

#ifndef F8_DECODE_HEADER
#define F8_DECODE_HEADER

// Table generated by opcodemaptool from f8 branch.
#define TRAP instruction_00
#define SUB_M instruction_01
#define SUB_NSP instruction_02
#define SUB_NNZ instruction_03
#define SUB_XH instruction_04
#define SUB_ZL instruction_05
#define SUB_YL instruction_06
#define SUB_YH instruction_07
#define SBC_M instruction_08
#define SBC_NSP instruction_0a
#define SBC_NNZ instruction_0b
#define SBC_XH instruction_0c
#define SBC_ZL instruction_0d
#define SBC_YL instruction_0e
#define SBC_YH instruction_0f
#define ADD_M instruction_10
#define ADD_I instruction_11
#define ADD_NSP instruction_12
#define ADD_NNZ instruction_13
#define ADD_XH instruction_14
#define ADD_YL instruction_15
#define ADD_ZL instruction_16
#define ADD_YH instruction_17
#define ADC_M instruction_18
#define ADC_I instruction_19
#define ADC_NSP instruction_1a
#define ADC_NNZ instruction_1b
#define ADC_XH instruction_1c
#define ADC_ZL instruction_1d
#define AND_YL instruction_1e
#define ADC_YH instruction_1f
#define CP_M instruction_20
#define CP_I instruction_21
#define CP_NSP instruction_22
#define CP_NNZ instruction_23
#define CP_XH instruction_24
#define CP_ZL instruction_25
#define CP_YL instruction_26
#define CP_YH instruction_27
#define OR_M instruction_28
#define OR_I instruction_29
#define OR_NSP instruction_2a
#define OR_NNZ instruction_2b
#define OR_XH instruction_2c
#define OR_ZL instruction_2d
#define OR_YL instruction_2e
#define OR_YH instruction_2f
#define SUBW_M instruction_30
#define LDW_A_SP instruction_31
#define SUBW_NSP instruction_32
#define SUBW_X instruction_33
#define SBCW_M instruction_34
#define LDW_DSP_A instruction_35
#define SBCW_NSP instruction_36
#define SBCW_X instruction_37
#define ADDW_M instruction_38
#define INC_NSP instruction_39
#define ADDW_NSP instruction_3a
#define ADDW_X instruction_3b
#define ADCW_M instruction_3c
#define ADCW_I instruction_3d
#define ADCW_NSP instruction_3e
#define ADCW_X instruction_3f
#define SLLW instruction_40
#define JRLE instruction_41
#define RRCW instruction_42
#define PREF_ALT3 0x43
#define SLLW_A_XL instruction_44
#define SRAW instruction_45
#define INCNW instruction_46
#define DECW_NSP instruction_47
#define JRNO instruction_48
#define PREF_ALT5 0x49
#define JRSLE instruction_4a
#define JP_A instruction_4c
#define JP_I instruction_4d
#define CALL_I instruction_4e
#define CALL_A instruction_4f
#define ADDW_I instruction_50
#define INC_M instruction_51
#define INC_A instruction_52
#define INC_NY instruction_53
#define DEC_NSP instruction_54
#define DEC_M instruction_55
#define DEC_A instruction_56
#define DEC_NY instruction_57
#define RRC_NSP instruction_58
#define RRC_M instruction_59
#define RRC_A instruction_5a
#define RRC_NY instruction_5b
#define RLC_NSP instruction_5c
#define RLC_M instruction_5d
#define RLC_A instruction_5e
#define RLC_NY instruction_5f
#define PUSH_NSP instruction_60
#define PUSH_M instruction_61
#define PUSH_A instruction_62
#define PUSH_NY instruction_63
#define JRNC instruction_64
#define JRC instruction_65
#define LDW_X_AM instruction_66
#define THRD instruction_68
#define SRLW instruction_69
#define POP_A instruction_6d
#define LDW_A_Z instruction_6e
#define AND_M instruction_70
#define XOR_I instruction_71
#define AND_NSP instruction_72
#define AND_NNZ instruction_73
#define XOR_XH instruction_74
#define AND_ZL instruction_75
#define ADC_YL instruction_76
#define AND_YH instruction_77
#define XOR_M instruction_78
#define AND_I instruction_79
#define XOR_NSP instruction_7a
#define XOR_NNZ instruction_7b
#define AND_XH instruction_7c
#define XOR_ZL instruction_7d
#define XOR_YL instruction_7e
#define XOR_YH instruction_7f
#define PUSHW_NSP instruction_80
#define PUSHW_M instruction_81
#define PUSHW_NNZ instruction_82
#define PUSHW_A instruction_83
#define LDW_AM_X instruction_84
#define LDW_Z_A instruction_85
#define TSTW1_NNZ instruction_86
#define TSTW1_A instruction_87
#define LDW_NAM_X instruction_88
#define PUSHW_I instruction_89
#define ADDW_SP_D instruction_8a
#define ADDW_A_D instruction_8b
#define LDI_YREL_Z instruction_8c
#define LDWI_YREL_Z instruction_8d
#define SEX instruction_8e
#define ZEX instruction_8f
#define TSTW1_NSP instruction_90
#define TSTW1_M instruction_91
#define JRSLT instruction_92
#define JRNZ instruction_93
#define JRSGE instruction_94
#define JRZ instruction_95
#define JRN instruction_96
#define JRNN instruction_97
#define MUL instruction_98
#define MSK instruction_99
#define RET instruction_9a
#define RETI instruction_9b
#define NEGW instruction_9c
#define MAD_M instruction_9d
#define MAD_NNZ instruction_9e
#define MAD_Z instruction_9f
#define XCH_A_NSP instruction_a0
#define XORW_M instruction_a1
#define XCH_A_Y instruction_a2
#define XCH_A_A instruction_a3
#define INCW_NSP instruction_a4
#define INCW_M instruction_a5
#define SBCW1_NNZ instruction_a6
#define INCW_A instruction_a7
#define ADCW1_NSP instruction_a8
#define ADCW1_M instruction_a9
#define ADCW1_NNZ instruction_aa
#define ADCW1_A instruction_ab
#define SBCW1_NSP instruction_ac
#define SBCW1_M instruction_ad
#define INCW_NNZ instruction_ae
#define SBCW1_A instruction_af
#define LDW_A_M instruction_b0
#define LDW_A_I instruction_b1
#define LDW_A_NSP instruction_b2
#define LDW_A_NNZ instruction_b3
#define LDW_A_AM instruction_b4
#define LDW_A_NY instruction_b5
#define LDW_A_X instruction_b6
#define LDW_A_D instruction_b7
#define LDW_NSP_A instruction_b8
#define PREF_SWAPOP 0xb9
#define LDW_NNZ_A instruction_ba
#define LDW_X_A instruction_bb
#define CPW instruction_bc
#define JR instruction_bd
#define POPW_A instruction_be
#define XCH_F_NSP instruction_bf
#define LD8_A_M instruction_c0
#define LD8_NY_A instruction_c1
#define LD8_A_NSP instruction_c2
#define LD8_A_NNZ instruction_c3
#define LD8_A_NY instruction_c4
#define LD8_A_Y instruction_c5
#define LD8_A_XH instruction_c6
#define LD8_A_YL instruction_c7
#define LD8_A_ZL instruction_c8
#define LD8_A_YH instruction_c9
#define LD8_A_ZH instruction_ca
#define LD8_M_A instruction_cb
#define LD8_NNZ_A instruction_cc
#define LD8_NSP_A instruction_cd
#define LD8_Y_A instruction_ce
#define BOOL_A instruction_cf
#define SRL_NSP instruction_d0
#define SRL_M instruction_d1
#define SRL_A instruction_d2
#define SRL_NY instruction_d3
#define SLL_NSP instruction_d4
#define SLL_M instruction_d5
#define SLL_A instruction_d6
#define SLL_NY instruction_d7
#define CLR_NSP instruction_d8
#define CLR_M instruction_d9
#define CLR_A instruction_da
#define CLR_NY instruction_db
#define TST_NSP instruction_dc
#define TST_M instruction_dd
#define TST_A instruction_de
#define TST_NY instruction_df
#define ORW_M instruction_e0
#define ORW_I instruction_e1
#define ORW_NSP instruction_e2
#define ORW_X instruction_e3
#define XCHW_Y_NSP instruction_e4
#define XCHW_X_Y instruction_e5
#define RRCW_NSP instruction_e6
#define RLCW_NSP instruction_e7
#define LD8_A_I instruction_e9
#define DNJNZ instruction_ea
#define CAX instruction_eb
#define PREF_ALT1 0xec
#define LDW_M_A instruction_ed
#define PREF_ALT2 0xee
#define RLCW_A instruction_ef
#define CLRW_NSP instruction_f0
#define CLRW_M instruction_f1
#define CLRW_NNZ instruction_f2
#define CLRW_A instruction_f3
#define ROT instruction_f4
#define PREF_ALT4 0xf5
#define SRA instruction_f6
#define DAA instruction_f7
#define CAXW instruction_f8
#define MAD_NSP instruction_fa
#define BOOLW instruction_fb
#define PUSH_I instruction_fc
#define XORW_I instruction_fd
#define XORW_NSP instruction_fe
#define XORW_X instruction_ff

#endif

/* End of f8.src/decode.h */

